spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finapp
    password: postgres
    username: postgres
  jpa:
    hibernate.ddl-auto: update

javax:
  persistence:
    schema-generation:
      create-source: metadata
